# Generated by Django 5.2.8 on 2025-11-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About / Profile', 'verbose_name_plural': 'About / Profile'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order'], 'verbose_name': 'Skill Category', 'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='about',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='about',
            name='short_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma separated technologies', max_length=400),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, help_text='e.g. Advanced / Intermediate / Beginner', max_length=80),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
